---
title: "md06demo.10.19"
author: "Andrew Myerson"
format: html
editor: visual
---

## MD 06 Demo In-Class 

```{r}
#| message: false
library(tidyverse)
library(moderndive)
library(ggthemes)
library(patchwork)
theme_set(theme_light())
```

```{r}
data(evals)
glimpse(evals)
```

```{r}
d <- evals |>
  rename(bty = bty_avg,    # just shorter to type
         sex = gender)     # actually what they have

glimpse(d)

```

```{r}
head(d)
```

```{r}
mod1 <- lm(score ~ bty,
           data = d)

get_regression_table(mod1)
```

```{r}
mod1_preds <- get_regression_points(mod1)

head(mod1_preds)
```

```{r,echo=FALSE}

ggplot(d,
       aes(x = bty,
           y = score)) +
  geom_jitter(alpha = .3) +
  geom_smooth(method = "lm",
              se = FALSE) +
  labs(x = "Beauty",
       y = "Evaluation",
       title = "Simple regression results")
```

```{r,echo=FALSE}

ggplot(mod1_preds,
       aes(x = bty,
           y = residual)) +
  geom_jitter(alpha = .3) +
  geom_hline(yintercept = 0,
             color = "blue") +
  labs(x = "Beauty",
       y = "Residual",
       title = "Simple regression residuals")
```
